const {
  STATUTS,
  PERMIS_CATEGORIES,
  GENRES,
  DOCUMENT_TYPES,
  INCIDENT_TYPES,
  INCIDENT_SEVERITES,
  idSchema,
  incidentIdSchema,
  documentIdSchema,
  listQuerySchema,
  createSchema,
  updateSchema,
  statusSchema,
  incidentCreateSchema,
  incidentUpdateSchema,
  tripSchema,
} = require('./driver.validator');

module.exports = {
  STATUTS,
  PERMIS_CATEGORIES,
  GENRES,
  DOCUMENT_TYPES,
  INCIDENT_TYPES,
  INCIDENT_SEVERITES,
  idSchema,
  incidentIdSchema,
  documentIdSchema,
  listQuerySchema,
  createSchema,
  updateSchema,
  statusSchema,
  incidentCreateSchema,
  incidentUpdateSchema,
  tripSchema,
};
