const {
  STATUTS,
  TYPES,
  CATEGORIES,
  MODES,
  SORTS,
  idSchema,
  listQuerySchema,
  statsQuerySchema,
  cancelSchema,
  failSchema,
  refundSchema,
  createPaymentSchema,
  updatePaymentSchema,
} = require('./payment.validator');

module.exports = {
  STATUTS,
  TYPES,
  CATEGORIES,
  MODES,
  SORTS,
  idSchema,
  listQuerySchema,
  statsQuerySchema,
  cancelSchema,
  failSchema,
  refundSchema,
  createPaymentSchema,
  updatePaymentSchema,
};
